// react-digital-clock/src/component/digital-clock.js
import React from 'react'
import ReactWebComponent from 'react-web-component'
import { string } from 'prop-types'

import './digital-clock.css';

const changeTimezone = (date, timezone) => {
    return new Date(date.toLocaleString('en-US', {
        timeZone: timezone
    }));
};

export default class DigitalClock extends React.Component {
    static propTypes = {
        timezone: string.isRequired,
    };

    constructor(props) {
        super(props);

        this.state = {
            localTime: new Date()
        };
    }

    /**
     * props is updated parsed by react-web-component just before invoking this
     * method but react doesn't detect this change to props so copy it to
     * state and use state instead.
     */
    webComponentConstructed() {
        this.setState(this.props)
    }

    webComponentConnected() {
        this.timer = setInterval(() => {
            this.setState({ localTime: new Date() });
        }, 1000);
    }

    webComponentDisconnected() {
        clearInterval(this.timer);
    }

    componentDidMount() {
        this.timer = setInterval(() => {
            this.setState({ localTime: new Date() });
        }, 1000);
    }

    render() {
        const { localTime } = this.state;
        const { timezone } = this.props;
        const time = changeTimezone(localTime, timezone);

        return (
            <div className="container">
                <h3>Timezone: {timezone}</h3>
                <div className="clock">
                    <div className="hour">{time.getHours()}</div>
                    <div className="minute">{time.getMinutes()}</div>
                    <div className="second">{time.getSeconds()}</div>
                </div>
            </div>
        )
    }
}

ReactWebComponent.create(<DigitalClock />, 'wc-digital-clock')

// stencil-digital-clock/src/components/ditigal-clock/digital-clock.tsx
import { Component, Prop, State } from '@stencil/core';

const changeTimezone = (date, timezone) => {
    return new Date(date.toLocaleString('en-US', {
        timeZone: timezone
    }));
};

@Component({
    tag: 'wc-digital-clock',
    styleUrl: 'digital-clock.css'
})
export class DigitalClock {

    private timer: number;

    @State() localTime: Date = new Date();

    @Prop() timezone: string;

    componentDidLoad() {
        this.timer = setInterval(() => {
            this.localTime = new Date();
        }, 1000);
    }

    componentDidUnload() {
        clearInterval(this.timer);
    }

    render() {
        const time = changeTimezone(this.localTime, this.timezone);
        return (
            <div class="container">
                <h3>Timezone: {this.timezone}</h3>
                <div class="clock">
                    <div class="hour">{time.getHours()}</div>
                    <div class="minute">{time.getMinutes()}</div>
                    <div class="second">{time.getSeconds()}</div>
                </div>
            </div>
        )
    }
}
